### PR TITLE
feat: support iCloud in China

### LINKED ISSUE #34: Can‘t use china id
It can‘t be used on the apple china id, and the login is restricted.

### PR DESCRIPTION
**Pull request by gutenye**
Closes #34 

Chinese iCloud uses a different domain (icloud.com.cn) instead of (icloud.com), this PR aims to support it.

## Test Plan

1. You need a Chinese Apple ID
2. Login https://www.icloud.com.cn/
3. Everything works as expected
4. Login https://www.icloud.com
5. It works as before

### CODE REVIEW

**Comment by gutenye** [comment]
@dedoussis, would you care to review when you have time?

**Comment by dedoussis** [comment]
Hi @gutenye, thanks for putting together this fix!

Have pushed a large change in the extension which affects your PR. Would you be happy with reworking this change to be compatible with the changes I introduced? If not, I'm happy to pick it up and rebase the implementation to what's currently in master.

**Comment by gutenye** [comment]
Rebased, I'm not able to test it because `npm start` failed with CSS errors

**Review by dedoussis — CHANGES_REQUESTED** [review]
Really appreciate the effort of re-implementing this on top of my recent changes.

Requested some refactoring changes to align this with the existing patterns of the code base.

I'd suggest that we don't read browser storage from within the ICloudClient, and instead pass the setupUrl as a constructor parameter. This will also require changes in the Popup and Options components.

Also, would you mind sharing the build errors you got?

**Comment by gutenye** [comment]
@dedoussis I got this error on the main branch when run `npm run start`, how do I fix it?

```
ERROR in ./src/pages/Popup/index.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
```

**Comment by dedoussis-stripe** [comment]
@gutenye I think the issue is related to the node version you're using. Try using node 18.

**Comment by dedoussis** [comment]
@gutenye given the complexity of the change, I took a stab at implementing support for CN: https://github.com/dedoussis/icloud-hide-my-email-browser-extension/pull/52

However, I don't have a CN iCloud account to test this. Would you be able to test my branch using your account?

**Pull request closed without merging**
